BTL_MVC/BTL_MVC/Models/Sanpham1.cs
namespace BTL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Sanpham1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham1()
        {
            ChiTietHDN = new HashSet<ChiTietHDN>();
            ChiTietHDX = new HashSet<ChiTietHDX>();
        }

        public int ID { get; set; }

        [StringLength(250)]
        public string TENSP { get; set; }

        [StringLength(250)]
        public string IMAGE { get; set; }

        public int? MALOAI { get; set; }

        [StringLength(250)]
        public string XUATXU { get; set; }

        public double? GIABAN { get; set; }

        public int? SOLUONG { get; set; }

        [StringLength(250)]
        public string Description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDN> ChiTietHDN { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDX> ChiTietHDX { get; set; }

        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}

BTL_MVC/BTL_MVC/Controllers/Sanpham1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using BTL_MVC.Models;
using Newtonsoft.Json;
using System.IO;
using System.Net.Http;
namespace BTL_MVC.Controllers
{
    public class Sanpham1Controller : Controller
    {
        private Model1 db = new Model1();

        // GET: api/SanPham
        string BASE_URI = "http://localhost:50338/api/sanpham1/";
        // GET: Sanpham1
        public ActionResult Index()//cái này ms gọi api
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-all");
                getTask.Wait();

                var result = getTask.Result;
                List<Sanpham1> p = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    p = JsonConvert.DeserializeObject<List<Sanpham1>>(data);
                }
                return View(p);
            }
        }

        // GET: Sanpham1/Details/5
        public ActionResult Details(int? id)
        {
            using (var client = new HttpClient())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-by-id/" + id);
                getTask.Wait();

                var result = getTask.Result;
                Sanpham1 room = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    room = JsonConvert.DeserializeObject<Sanpham1>(data);
                }
                return View(room);
            }
        }

        // GET: Sanpham1/Create

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IMAGE,Description,TENSP,SOLUONG,MALOAI,XUATXU,GIABAN")] SanPhamViewModel sanpham1)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(BASE_URI);

                    string data = JsonConvert.SerializeObject(sanpham1);
                    StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

                    var putTask = client.PostAsync("create", content);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(sanpham1);
        }
        public ActionResult Timkiem(string name, int? page)
        {

            IEnumerable<Sanpham1> obj = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("http://localhost:50338/api/sanpham1/api/GetProductname/");
            var data = hc.GetAsync("GetProductname?name=" + name);
            data.Wait();
            var readdata = data.Result;
            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IEnumerable<Sanpham1>>();
                displaydata.Wait();
                obj = displaydata.Result;
            }
            return View(obj);
        }
        // GET: Sanpham1/Edit/5
        public ActionResult Edit(int? id)
        {
            using (var client = new HttpClient())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-by-id/" + id);
                getTask.Wait();

                var result = getTask.Result;
                Sanpham1 room = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    room = JsonConvert.DeserializeObject<Sanpham1>(data);
                }
                return View(room);
            }
        }

        // POST: Sanpham1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IMAGE,Description,TENSP,SOLUONG,MALOAI,XUATXU,GIABAN")] Sanpham1 sanpham1)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(BASE_URI);

                    string data = JsonConvert.SerializeObject(sanpham1);
                    StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

                    var putTask = client.PutAsync("update", content);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(sanpham1);
        }

        // GET: Sanpham1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-by-id/" + id);
                getTask.Wait();

                var result = getTask.Result;
                Sanpham1 room = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    room = JsonConvert.DeserializeObject<Sanpham1>(data);
                }
                return View(room);
            }
        }
        // POST: Sanpham1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BASE_URI);

                var deleteTask = client.DeleteAsync("delete/" + id);
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL_MVC/BTL_MVC/Views/Sanpham1/Create.cshtml
@model BTL_MVC.Models.SanPhamViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Sanpham1</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TENSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            <div class="form-group">
                <label>Hình Ảnh</label>
                <input type="file" id="image" name="IMAGE" />
            </div>

        </div>*@
    <div class="form-group" id="selectImage">
        @Html.LabelFor(model => model.IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
           
            <input type="file" id="image" name="IMAGE" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MALOAI, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MALOAI, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MALOAI, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.XUATXU, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.XUATXU, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.XUATXU, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GIABAN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GIABAN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GIABAN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SOLUONG, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SOLUONG, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SOLUONG, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BTL_MVC/BTL_MVC/Views/Sanpham1/Delete.cshtml
@model BTL_MVC.Models.Sanpham1

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sanpham1</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TENLOAI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TENLOAI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TENSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.XUATXU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.XUATXU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GIABAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIABAN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SOLUONG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SOLUONG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BTL_MVC/BTL_MVC/Views/Sanpham1/Details.cshtml
@model BTL_MVC.Models.Sanpham1

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Sanpham1</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TENLOAI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TENLOAI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TENSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.XUATXU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.XUATXU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GIABAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIABAN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SOLUONG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SOLUONG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BTL_MVC/BTL_MVC/Views/Sanpham1/Edit.cshtml
@model BTL_MVC.Models.Sanpham1

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sanpham1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TENSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IMAGE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IMAGE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div  class="col-md-10">
                <label class = "control-label col-md-2">MÃ Loại</label>
                <input class = "text-danger" type="text" class="form-control" id="donGia" name="MALOAI" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.XUATXU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.XUATXU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.XUATXU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GIABAN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIABAN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GIABAN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SOLUONG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SOLUONG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SOLUONG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BTL_MVC/BTL_MVC/Views/Sanpham1/Index.cshtml
@model IEnumerable<BTL_MVC.Models.Sanpham1>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
 
<button type="button" class="btn btn-primary"style="background: bottom;" > @Html.ActionLink("Thêm Sản Phẩm", "Create")</button>
<p>
   
</p>
<div class="col-md-4" style="margin-top: 60px">
    @using (Html.BeginForm("Timkiem", "SanPham1", FormMethod.Get))
    {
        <input style="height:30px;width:250px;" class="search-txt" type="text" id="name" name="name" placeholder="Từ khóa">
        <button style="height: 30px; margin-left: -10px; width: 45px; background-color: lightsteelblue;" id="btnSearch" class="search-btn" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>

    }
</div>
<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>
                Mã SP
            </td>
            <td style="max-width:7%;">
                Hình Ảnh
            </td>
            <td>
                Tên Sản Phẩm
            </td>
            <td>
                Mã Loại
            </td>
            <td>
                Xuất Xứ
            </td>



            <td>
                Mô tả
            </td>

            <td>
                Đơn Giá
            </td>

            <td>
                Sửa
            </td>
            <td>
               Xem
            </td>
            <td>Xóa</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.ID
            </td>
            <td>
                <img src="/Content/image/@item.IMAGE" class="profile-user-img img-responsive" />
            </td>


            <td>
                @item.TENSP
            </td>
            <td>
                @item.MALOAI
            </td>
            <td>
                @item.XUATXU
            </td>


            <td>
                @item.Description
            </td>

            <td style="color:red;">
                @string.Format("{0:#,##0}", item.GIABAN)đ
            </td>

            <td><a class="btn btn-primary" href="@Url.Action("Edit","Sanpham1")/@item.ID">Edit</a></td>
            <td><a class="btn btn-primary" href="@Url.Action("Details","Sanpham1")/@item.ID">Deatails</a></td>

            <td><a class="btn btn-primary" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","Sanpham1")/@item.ID">Xóa</a></td>

        </tr>
        }

</table>

BTL_MVC/BTL_MVC/Views/Sanpham1/Timkiem.cshtml
@model IEnumerable<BTL_MVC.Models.Sanpham1>

<p>
    <button type="button" class="btn btn-primary" style="background: bottom;">@Html.ActionLink("Quay Lại", "Index")</button>
</p>
<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>
                Mã SP
            </td>
            <td style="max-width:7%;">
                Hình Ảnh
            </td>
            <td>
                Tên Sản Phẩm
            </td>
            <td>
                Mã Loại
            </td>
            <td>
                Xuất Xứ
            </td>



            <td>
                Mô tả
            </td>

            <td>
                Đơn Giá
            </td>

            <td>
                Sửa
            </td>
            <td>
                Xem
            </td>
            <td>Xóa</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.ID
                </td>
                <td>
                    <img src="/Content/image/@item.IMAGE" class="profile-user-img img-responsive" />
                </td>


                <td>
                    @item.TENSP
                </td>
                <td>
                    @item.MALOAI
                </td>
                <td>
                    @item.XUATXU
                </td>


                <td>
                    @item.Description
                </td>

                <td style="color:red;">
                    @string.Format("{0:#,##0}", item.GIABAN)đ
                </td>

                <td><a class="btn btn-primary" href="@Url.Action("Edit","Sanpham1")/@item.ID">Edit</a></td>
                <td><a class="btn btn-primary" href="@Url.Action("Details","Sanpham1")/@item.ID">Deatails</a></td>

                <td><a class="btn btn-primary" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","Sanpham1")/@item.ID">Xóa</a></td>

            </tr>
        }

</table>