BTL_MVC/BTL_MVC/Models/NhaCungCap.cs
namespace BTL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("NhaCungCap")]
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            HoaDonNhap = new HashSet<HoaDonNhap>();
        }

        public int ID { get; set; }

        [StringLength(250)]
        public string TENNCC { get; set; }

        [StringLength(250)]
        public string DIACHI { get; set; }

        public int? SODIENTHOAI { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonNhap> HoaDonNhap { get; set; }
    }
}

BTL_MVC/BTL_MVC/Controllers/NhaCungCapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using BTL_MVC.Models;
using Newtonsoft.Json;

namespace BTL_MVC.Controllers
{
    public class NhaCungCapsController : Controller
    {
        private Model1 db = new Model1();

        
        string BASE_URI = "http://localhost:50338/api/NhaCungCap/";
        // GET: NhaCungCaps
        public ActionResult Index()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-all");
                getTask.Wait();

                var result = getTask.Result;
                List<NhaCungCap> p = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    p = JsonConvert.DeserializeObject<List<NhaCungCap>>(data);
                }
                return View(p);
            }
        }
        //timkiem
        public ActionResult Timkiem(string name, int? page)
        {

            IEnumerable<NhaCungCap> obj = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("http://localhost:50338/api/NhaCungCap/api/GetProductname/");
            var data = hc.GetAsync("GetProductname?name=" + name);
            data.Wait();
            var readdata = data.Result;
            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IEnumerable<NhaCungCap>>();
                displaydata.Wait();
                obj = displaydata.Result;
            }
            return View(obj);
        }

        // GET: NhaCungCaps/Details/5
        public ActionResult Details(int? id)
        {
            using (var client = new HttpClient())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-by-id/" + id);
                getTask.Wait();

                var result = getTask.Result;
                NhaCungCap room = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    room = JsonConvert.DeserializeObject<NhaCungCap>(data);
                }
                return View(room);
            }
        }

        // GET: NhaCungCaps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NhaCungCaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TENNCC,DIACHI,SODIENTHOAI")] NhaCungCap nhaCungCap)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(BASE_URI);

                    string data = JsonConvert.SerializeObject(nhaCungCap);
                    StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

                    var putTask = client.PostAsync("create", content);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(nhaCungCap);
        }

        // GET: NhaCungCaps/Edit/5
        public ActionResult Edit(int? id)
        {
            using (var client = new HttpClient())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-by-id/" + id);
                getTask.Wait();

                var result = getTask.Result;
                NhaCungCap room = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    room = JsonConvert.DeserializeObject<NhaCungCap>(data);
                }
                return View(room);
            }
        }

        // POST: NhaCungCaps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TENNCC,DIACHI,SODIENTHOAI")] NhaCungCap nhaCungCap)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(BASE_URI);

                    string data = JsonConvert.SerializeObject(nhaCungCap);
                    StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

                    var putTask = client.PutAsync("update", content);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(nhaCungCap);
        }


        // GET: NhaCungCaps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BASE_URI);

                var getTask = client.GetAsync("get-by-id/" + id);
                getTask.Wait();

                var result = getTask.Result;
                NhaCungCap room = null;
                if (result.IsSuccessStatusCode)
                {
                    string data = result.Content.ReadAsStringAsync().Result;
                    room = JsonConvert.DeserializeObject<NhaCungCap>(data);
                }
                return View(room);
            }
        }

        // POST: NhaCungCaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BASE_URI);

                var deleteTask = client.DeleteAsync("delete/" + id);
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL_MVC/BTL_MVC/Views/NhaCungCaps/Create.cshtml
@model BTL_MVC.Models.NhaCungCap

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{   
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhaCungCap</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TENNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SODIENTHOAI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SODIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SODIENTHOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTL_MVC/BTL_MVC/Views/NhaCungCaps/Delete.cshtml
@model BTL_MVC.Models.NhaCungCap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhaCungCap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TENNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIACHI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SODIENTHOAI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SODIENTHOAI)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BTL_MVC/BTL_MVC/Views/NhaCungCaps/Details.cshtml
@model BTL_MVC.Models.NhaCungCap

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NhaCungCap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TENNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIACHI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SODIENTHOAI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SODIENTHOAI)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BTL_MVC/BTL_MVC/Views/NhaCungCaps/Edit.cshtml
@model BTL_MVC.Models.NhaCungCap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhaCungCap</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TENNCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENNCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SODIENTHOAI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SODIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SODIENTHOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTL_MVC/BTL_MVC/Views/NhaCungCaps/Index.cshtml
@model IEnumerable<BTL_MVC.Models.NhaCungCap>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <button type="button" class="btn btn-primary" style="background: bottom;"> @Html.ActionLink("Thêm Nhà Cung Cấp", "Create")</button>
</p>
<div class="col-md-4" style="margin-top: 60px">
    @using (Html.BeginForm("Timkiem", "NhaCungCaps", FormMethod.Get))
    {
        <input style="height:30px;width:250px;" class="search-txt" type="text" id="name" name="name" placeholder="Từ khóa">
        <button style="height: 30px; margin-left: -10px; width: 45px; background-color: lightsteelblue;" id="btnSearch" class="search-btn" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>

    }
</div>
<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>
                ID
            </td>

            <td>
                Tên Nhà Cung Cấp
            </td>

            <td>
                Địa Chỉ
            </td>
            <td>
                Số Điện Thoại
            </td>
            <td>
                Sửa
            </td>
            <td>
                Xem
            </td>
            <td>Xóa</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.ID
            </td>
            <td>
                @item.TENNCC
            </td>
            <td>
                @item.DIACHI
            </td>
            <td>
                @item.SODIENTHOAI
            </td>
            <td><a class="btn btn-primary" href="@Url.Action("Edit","NhaCungCaps")/@item.ID">Edit</a></td>
            <td><a class="btn btn-primary" href="@Url.Action("Details","NhaCungCaps")/@item.ID">Deatails</a></td>

            <td><a class="btn btn-primary" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","NhaCungCaps")/@item.ID">Xóa</a></td>

        </tr>
        }

</table>

BTL_MVC/BTL_MVC/Views/NhaCungCaps/Timkiem.cshtml
@model IEnumerable<BTL_MVC.Models.NhaCungCap>

@{
    ViewBag.Title = "Timkiem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Timkiem</h2>

<p>
    <button type="button" class="btn btn-primary" style="background: bottom;">@Html.ActionLink("Quay Lại", "Index")</button>
</p>
<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>
                ID
            </td>

            <td>
                Tên Nhà Cung Cấp
            </td>

            <td>
                Địa Chỉ
            </td>
            <td>
                Số Điện Thoại
            </td>
            <td>
                Sửa
            </td>
            <td>
                Xem
            </td>
            <td>Xóa</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.ID
            </td>



            <td>
                @item.TENNCC
            </td>
            <td>
                @item.DIACHI
            </td>
            <td>
                @item.SODIENTHOAI
            </td>


            <td><a class="btn btn-primary" href="@Url.Action("Edit","NhaCungCaps")/@item.ID">Edit</a></td>
            <td><a class="btn btn-primary" href="@Url.Action("Details","NhaCungCaps")/@item.ID">Deatails</a></td>

            <td><a class="btn btn-primary" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","NhaCungCaps")/@item.ID">Xóa</a></td>

        </tr>
        }

</table>